version: "3.8"

services:

  nginx-prometheus-exporter:
    container_name: ${CONTAINER_NPEXPORTER}
    image: nginx/nginx-prometheus-exporter:0.11.0
    restart: unless-stopped
    environment:
      TZ: Asia/Tehran
    ports:
      - "${PUB_NPEXPORTER_PORT}:9113"
    command:
      - -nginx.scrape-uri
      - http://${CONTAINER_NGINX}:8080/stub_status
    depends_on:
      - nginx

  prometheus:
    container_name: ${CONTAINER_PROMETHEUS}
    image: prom/prometheus:v2.30.3
    restart: unless-stopped
    environment:
      TZ: Asia/Tehran
    ports:
      - "${PUB_PROMETHEUS_PORT}:9090"
    volumes:
      - ./docker/prometheus:/etc/prometheus:ro
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    container_name: ${CONTAINER_GRAFANA}
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      TZ: Asia/Tehran
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      #- ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "${PUB_GRAFANA_PORT}:3000"

volumes:
  prometheus-data:
  grafana-data:
